[package]
name = "solana-wallet-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
solana-client = "2.1.4"
solana-sdk = "2.1.4"
tiny-bip39 = "2.0.0"
